language: python
python:
  - "3.5"

install:
  - "sudo apt-get update -q"
  - "sudo apt-get install -y python3-lxml"
  - "pip install --upgrade pip"
  - "pip install -r ./travis/requirements.txt"
  - "pip install -r ./requirements.txt"

script:
  - "python ./travis/test_json.py"
  - "py.test . -v --cov . --cov-report term-missing"

after_success:
  - "coveralls"
  
env:
  - PYTHONPATH=.

notifications:
  irc:
    channels:
      - "irc.esper.net#himself"
    template:
      - "%{repository} #%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Commit message : %{commit_message}"
      - "Build details: %{build_url}"
      - "Change view : %{compare_url}"
  on_failure: always
  on_success: always
  skip_join: false
